version: 1
project:
  id: Cefiyana1/teatestproject
  name: TeaTestProject
  description: Ini adalah project dummy untuk eksperimen Tea Protocol
  url: https://github.com/Cefiyana1/teatestproject
maintainers:
  - Cefiyana1
governance:
  quorum: 1
