name: Tea Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-tea:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tea
        run: |
          curl -fsSL https://install.tea.xyz | sh

      - name: Add tea to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run tea check
        run: tea check
