name: Tea Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-tea:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Tea
        run: |
          curl -fsSL https://install.tea.xyz | bash
          echo "$HOME/.tea/bin" >> $GITHUB_PATH

      - name: Verify Tea Installation
        run: |
          ls -la $HOME/.tea/bin
          tea --version

      - name: Run tea check
        run: |
          tea check
