name: Tea Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-tea:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Tea
        run: |
          curl -fsSL https://install.tea.xyz | sh
          echo "$HOME/.tea/bin" >> $GITHUB_PATH
      - name: Verify Tea Installation
        run: |
          echo "Tea installation directory:"
          ls -l $HOME/.tea/bin
          echo "Tea version:"
          $HOME/.tea/bin/tea --version
      - name: Run tea check
        run: |
          $HOME/.tea/bin/tea check
