name: Tea Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-tea:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tea
        run: |
          curl -fsSL https://install.tea.xyz | sh
      - name: Add Tea to PATH
        run: |
          echo "export PATH=$HOME/.tea/bin:$PATH" >> $GITHUB_ENV
      - name: Verify Tea installation
        run: |
          echo "Tea installation directory:"
          ls -la $HOME/.tea/bin
      - name: Run tea check
        run: tea check
